INSERT INTO category(name, created_at) values ('Eletronicos', NOW());
INSERT INTO category(name, created_at) values ('Escritorio', NOW());
INSERT INTO category(name, created_at) values ('Computadores', NOW());
INSERT INTO category(name, created_at) values ('Livros', NOW());
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('Smart TV',2900,'UN','https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/2-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('Mackbook Pro',1250,'UN','https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/3-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('Pc Gamer',1250,'UN','https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/4-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('Rails for Dummies',100.99,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/5-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Ex',1350.0,'UN','https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/6-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer X', 1350.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/7-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Alfa', 1850.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/8-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Tera', 1950.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/9-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Y', 1700.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/10-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Nitro', 2450.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/11-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Card', 2350.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/12-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Plus', 1950.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/13-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Hera', 1120.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/14-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Week', 1220.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/15-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Max', 1430.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/16-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Turbo', 1590.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/17-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Hot', 1200.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/18-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Ez', 1650.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/19-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Tr', 1250.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/20-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Tx', 1450.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/21-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Er', 1650.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/22-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Min', 1750.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/23-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Boo', 1850.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/24-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Foo', 1950.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/25-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('PC Gamer Xoo', 4170.0,'UN', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/25-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('Java Fundamentos',60,'UN','https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('Java Intermediario',70,'UN','https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO product(name, sale_price, unit_measure,image_url) values ('O Senhor dos Aneis',70,'UN','https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg');
INSERT INTO product_category (product_id, category_id) values (1, 2);
INSERT INTO product_category (product_id, category_id) values (2, 1);
INSERT INTO product_category (product_id, category_id) values (2, 3);
INSERT INTO product_category (product_id, category_id) values (3, 3);
INSERT INTO product_category (product_id, category_id) values (4, 3);
INSERT INTO product_category (product_id, category_id) values (4, 4);
INSERT INTO product_category (product_id, category_id) values (5, 2);
INSERT INTO product_category (product_id, category_id) values (6, 3);
INSERT INTO product_category (product_id, category_id) values (7, 3);
INSERT INTO product_category (product_id, category_id) values (8, 3);
INSERT INTO product_category (product_id, category_id) values (9, 3);
INSERT INTO product_category (product_id, category_id) VALUES (10, 3);
INSERT INTO product_category (product_id, category_id) VALUES (11, 3);
INSERT INTO product_category (product_id, category_id) VALUES (12, 3);
INSERT INTO product_category (product_id, category_id) VALUES (13, 3);
INSERT INTO product_category (product_id, category_id) VALUES (14, 3);
INSERT INTO product_category (product_id, category_id) VALUES (15, 3);
INSERT INTO product_category (product_id, category_id) VALUES (16, 3);
INSERT INTO product_category (product_id, category_id) VALUES (17, 3);
INSERT INTO product_category (product_id, category_id) VALUES (18, 3);
INSERT INTO product_category (product_id, category_id) VALUES (19, 3);
INSERT INTO product_category (product_id, category_id) VALUES (20, 3);
INSERT INTO product_category (product_id, category_id) VALUES (21, 3);
INSERT INTO product_category (product_id, category_id) VALUES (22, 3);
INSERT INTO product_category (product_id, category_id) VALUES (23, 3);
INSERT INTO product_category (product_id, category_id) VALUES (24, 3);
INSERT INTO product_category (product_id, category_id) VALUES (25, 3);