INSERT INTO categoria(nome) values ('Eletronico');
INSERT INTO categoria(nome) values ('Escritorio');
INSERT INTO categoria(nome) values ('Computadores');
INSERT INTO categoria(nome) values ('Livros');
INSERT INTO produto(nome, preco, unidade) values ('notebook',100,'UN');
INSERT INTO produto(nome, preco, unidade) values ('mouse',40,'UN');
INSERT INTO produto(nome, preco, unidade) values ('teclado',80,'UN');
INSERT INTO produto(nome, preco, unidade) values ('Java Fundamentos',60,'UN');
INSERT INTO produto(nome, preco, unidade) values ('Java Intermediario',70,'UN');
INSERT INTO produto_categoria (produto_id,categoria_id) values (1,1);
INSERT INTO produto_categoria (produto_id,categoria_id) values (1,3);
INSERT INTO produto_categoria (produto_id,categoria_id) values (2,3);
INSERT INTO produto_categoria (produto_id,categoria_id) values (3,3);
INSERT INTO produto_categoria (produto_id,categoria_id) values (4,4);
INSERT INTO produto_categoria (produto_id,categoria_id) values (5,4);
